from django.urls import path
from . import views


urlpatterns = [
    path("", views.index, name="home"),
    path("index", views.index),
    path("patient", views.patient, name="patient"),
    path("doctor", views.doctor, name="doctor"),
    path("admins", views.admins, name="admins"),
    path("create", views.patient_create, name="patient_create_account"),
    path('login-patient', views.login_patient, name='login_patient'),
    path('login-admin', views.login_admin, name='login_admin'),
    path('login-doctor', views.login_doctor, name='login_doctor'),
    path('admin-index', views.admin_index, name='admin_index'),
    path('doctor-index', views.doctor_index, name='doctor_index'),
    path('patient-index', views.patient_index, name='patient_index'),
    path('patient-table-admin', views.patient_table_admin, name='patient_table_admin'),
    path('doctor-table-admin', views.doctor_table_admin, name='doctor_table_admin'),
    path('appointment-table-admin', views.appointment_table_admin, name='appointment_table_admin'),
    path('report-table-admin', views.report_table_admin, name='report_table_admin'),
    path('create-patient', views.create_patient, name='create_patient'),
    path('create-patient-admin', views.create_patient_admin, name='create_patient_admin'),
    path('delete-patient-admin', views.delete_patient_admin, name='delete_patient_admin'),
    path('create-report-admin', views.create_report_admin, name='create_report_admin'),
    path('delete-report-admin', views.delete_report_admin, name='delete_report_admin'),
    path('create-doctor-admin', views.create_doctor_admin, name='create_doctor_admin'),
    path('delete-doctor-admin', views.delete_doctor_admin, name='delete_doctor_admin'),
    path('create-appointment-admin', views.create_appointment_admin, name='create_appointment_admin'),
    path('delete-appointment-admin', views.delete_appointment_admin, name='delete_appointment_admin'),
    path('report-table-patient', views.report_table_patient, name='report_table_patient'),
    path('create-report-patient', views.create_report_patient, name='create_report_patient'),
    path('delete-report-patient', views.delete_report_patient, name='delete_report_patient'),
    path('doctor-table-patient', views.doctor_table_patient, name='doctor_table_patient'),
    path('doctor_select_patient', views.doctor_select_patient, name='doctor_select_patient'),
    path('appointment-table-patient', views.appointment_table_patient, name='appointment_table_patient'),
    path('update-appointment-patient', views.update_appointment_patient, name='update_appointment_patient'),
    path('delete-appointment-patient', views.delete_appointment_patient, name='delete_appointment_patient'),
    path('create-appointment-patient', views.create_appointment_patient, name='create_appointment_patient')
]